version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      -POSTGRES_USER: postgres
      -POSTGRES_PASSWORD: root
      -POSTGRES_DB: devops
    ports:
       - 5434:5432
    volumes:
       - postgres-data:/var/lib/postgresql/data
  app-devops-back:
    depends_on:
      - postgres
    image: ahmedfredj/devops-back
    restart: on-failure
    ports:
      - 8999:8999
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.ur" : "jdbc:postgresql://postgres:5432/devops",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQL81Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db :