version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: devops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
  app-timesheet:
    depends_on:
      - postgresdb
    image: ahmedfredj/devops-back:1.0.0
    restart: on-failure
    ports:
      - "8999:8999"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://localhost:5432/devops?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db:
